version: '3.8'

services:
  # Base de données MongoDB
  mongo:
    image: mongo
    container_name: mongo-nutriwiser
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nutriwiser
      - MONGO_INITDB_ROOT_PASSWORD=nutriwiser
    ports:
      - "27017:27017"
    volumes:
      - mongdata:/data/db
    restart: unless-stopped

  # Base de données MySQL
  mysql:
    image: mysql:8
    container_name: mysql-nutriwiser
    environment:
      - MYSQL_ROOT_PASSWORD=nutriwiser
      - MYSQL_DATABASE=nutriwiser_db
      - MYSQL_USER=nutriwiser
      - MYSQL_PASSWORD=nutriwiser
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped 

  # PHPMyAdmin pour MySQL
  phpmyadmin:                                                             
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-nutriwiser
    environment:
      PMA_HOST: mysql
      PMA_USER: nutriwiser
      PMA_PASSWORD: nutriwiser
    ports:
      - "8080:80"
    depends_on:
      - mysql
  
 
volumes:
  mongdata:
  mysqldata: